version: "3.7"
services:
  sibico-backend:
    container_name: sibico-backend
    command: "bash startup.sh"
    build:
      context: .
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@sibico-postgres/sibico?schema=public
    ports:
      - 5001:5001
    depends_on:
      - sibico-postgres
  sibico-postgres:
    container_name: sibico-postgres
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sibico
    volumes:
      - postgres-data:/var/lib/postgresql/data
  populate-db:
    container_name: populate-db
    build: populate_db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@sibico-postgres/sibico?schema=public
    command: "tail -f /dev/null"
    depends_on:
      - sibico-backend
    volumes:
      - ./upload:/home/upload
      - ./populate_db:/home/populate_db
volumes:
  upload: {}
  postgres-data: {}
