version: "3.7"
services:
  sibico-backend:
    environment:
      - PUBLIC_IP=localhost
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@sibico-postgres/sibico?schema=public
    env_file: .env
    restart: "no"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
volumes:
  node_modules: {}
  dist: {}
