version: "3.7"
services:
  sibico-backend:
    container_name: sibico-backend
    image: sibico-backend:latest
    command: "npm start"
    build:
      context: .
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@sibico-postgres/sibico?schema=public
    ports:
      - 5000:5000
    depends_on:
      - sibico-postgres
  sibico-postgres:
    container_name: sibico-postgres
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sibico
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: {}
