version: "3.7"
services:
  sibico-backend:
    container_name: sibico-backend
    command: "npm start"
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@sibico-postgres/sibico?schema=public
    env_file: .env
    ports:
      - 5000:5000
    depends_on:
      - sibico-postgres
  sibico-postgres:
    container_name: sibico-postgres
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sibico
    volumes:
      - postgres-data:/var/lib/postgresql/data

  populate-db:
    container_name: populate-db
    build: populate_db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@sibico-postgres/sibico?schema=public
    command: "python3 main.py"
    depends_on:
      - sibico-backend
    volumes:
      - ./upload:/home/upload
      - ./populate_db:/home/populate_db
volumes:
  upload: {}
  postgres-data: {}
